name: risk_score_model_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - numpy=1.21.2
  - pandas=1.3.4
  - scikit-learn=1.0
  - pip:
    - azureml-defaults==1.45.0
    - inference-schema==1.4.1
    - azureml-core==1.45.0
    - joblib==1.1.0
